version: '3.1'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - postgres

  db:
    image: postgres:13-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: kt-pub
      POSTGRES_USER: kt-pub
      POSTGRES_PASSWORD: change_password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
