ktor:
  application:
    modules:
      - com.rutubishi.ApplicationKt.testModule
  deployment:
    port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"